### ISSUE TITLE
Building trade statistics report issues

### ISSUE THREAD

**Issue by JosephCrispell** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#108]
### Description

Having a few issues when building the final trade statistics report with the `3_buildMonthlyReport.Rmd`.

### Issues/tasks

- [ ] NSDP Table: possible to make it more compact so doesn't take up as much space - *can't reduce text further I don't think - possible could change [row padding](https://davidgohel.github.io/flextable/reference/padding.html)*
- [ ] Trade Balance Map: couldn't add a title for some reason *works ok for me using [`ggtitle("My new title")`](http://www.sthda.com/english/wiki/ggplot2-title-main-axis-and-legend-titles) function
- [ ] Principle Exports and Imports: above the key give title "Monthly Trend Analysis", get rid of dots in between words, and dates at the bottom of graph sometimes not formatted correctly
      - *Legend title can use `guides(color=guide_legend(title="New Legend Title"))`*
      - *Change this line for the dots:* https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/47af86a8b3e7e53d9f44f5efe0717ce6da99af02/R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd#L799-L801
      - *Date formatting - when there are only a few years it is adding decimal points - should be able to [customise](http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels) this*
- [ ] Imports of dietary risk factors for NCDs: couldn't work out how to choose the top five from the current month and then append to historical data to have top five time series analysis for current month - *use the [`arrange()`](https://dplyr.tidyverse.org/reference/arrange.html) to order and then [`top_n`](https://rdrr.io/cran/dplyr/man/top_n.html) to select (or [`order()`](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/order) and `head()` functions*
- [ ] Produced domestically: there are problems with merging, something is happening because the 0 is dropping off from the front of chicken and chicken eggs. Have tried different things including padding but still not working, and chicken products are in the processed data. the classification file is OPN_FINAL_ASY_FishChickenImportSubClassifications_31-01-20.csv
   - *Is it worth moving this merging step into the `1_processLatestMonthsTradeStats.R` script*: https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/47af86a8b3e7e53d9f44f5efe0717ce6da99af02/R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd#L997-L999
   - *The merging does appear to pull in the "Livestock Substitution column" successfully pulling in the following types:*
      ```
      Canned Mackerel    Canned Tunas         Chicken    Chicken Eggs 
              5              12                17                 2
     ```
    - *Likely to be an issue with some processing steps that follow or on historic data merging*

**Comment by hugo-e-pigott** [comment]
Hi Joe just couple things for the report:

- We reviewed it today, and people felt that report on targets annually- so have taken these out
- Is it possible to make the images produced in word have a higher resolution?
- The report is being produced in word on a Microsoft computer, however still have some formatting issues, including "trade Balance for Pacific nIslands not included"
-
[3_buildMonthlyReport_v1.docx](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7536946/3_buildMonthlyReport_v1.docx)

- Need to divide all value in the trade by trade agreement table by 1,000,000
- The information is still not added to the keys

**Comment by hugo-e-pigott** [comment]
- Also have tried to take out the dot separator in number of ways, still not sure what I am doing wrong

**Comment by JosephCrispell** [comment]
> Is it possible to make the images produced in word have a higher resolution?

I think the best option here is to make the figures bigger and play around with the axis font sizes. Use the `fig.width`, 
 and `fig.height` Rmd code cell options to change the figure size and the options within `theme()` to modify axis text sizes. Also it's worth consider removing the two columns from the `styles_reference.docx` style template to make it one column per page.

---

> The report is being produced in word on a Microsoft computer, however still have some formatting issues, including "trade Balance for Pacific nIslands not included"

The "trade Balance for Pacific nIslands not included" appears to have disappeared off the page - this didn't happen in my build but I've added some blank lines under map to push this section onto next page and ensure it isn't lost. To add blank lines you add `"&nbsp;  "`, for example I added 9 lines to push seciton 3 onto the next page with:
```
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
```
*Note the two paces after `&nbsp;`!*

---

> Need to divide all value in the trade by trade agreement table by 1,000,000

Added `tradeByTradeAgreement[, -1] <- tradeByTradeAgreement[, -1] / 1000000` for this

---

> The information is still not added to the keys have tried using this, not sure why not working 
"guides(color=guide_legend(title="New Legend Title"))"

This was caused by having `legend.title=element_blank()` in the `theme()` function call, which removes the legend title - sorted now.

---

> Also have tried to take out the dot separator in number of ways, still not sure what I am doing wrong

Sorry I misread the code, the following works and I've updated the code:
```r
totalMajorImports$name_shortened <- sapply(totalMajorImports$name, 
                                           FUN=split_sentence_across_lines, 
                                           word_separator = "\\.")
totalMajorImports$name_shortened <- gsub("\\.", " ", totalMajorImports$name_shortened)
```
The `sapply()` is applying the `split_sentence_across_lines()` is splitting the long column names across lines - column names have words separated by "." so using this here. The `gsub()` then takes these column names split across lines (when too long) and replaces the "." with spaces.

---

The `# Imports of Dietary Risk Factors for Noncommunicable Diseases` and `# Imports of food and products targeted as those that can be produced domestically` sections aren't building for me as I don't have the most up to date version of `OUT_PROC_ASY_ProcessedRawData_31-10-21.csv` with unhealthy food categories merged in

**Comment by hugo-e-pigott** [comment]
[OUT_PROC_ASY_ProcessedRawData_31-10-21.csv](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7543496/OUT_PROC_ASY_ProcessedRawData_31-10-21.csv)

**Comment by hugo-e-pigott** [comment]
No data set above, use one below:

[OUT_PROC_ASY_ProcessedRawData_31-10-21.csv](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7543778/OUT_PROC_ASY_ProcessedRawData_31-10-21.csv)

**Comment by JosephCrispell** [comment]
Hi @hugo-e-pigott,

Apologies for not getting this sorted earlier - Ijust pushed a couple of minor changes to decrease legend size and increase tick frequency. Will email over report shortly.

Thanks,

Joe
