### ISSUE TITLE
Code going from R to Excel 

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#113]
Below are:
- Tables up to June
- Tables up to July after running R
- Raw data for July
- Processed data for July
[SEC_FINAL_MAN_FinalTradeStatisticsTables_30-06-21_WORKING.xlsx](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7690237/SEC_FINAL_MAN_FinalTradeStatisticsTables_30-06-21_WORKING.xlsx)

[SEC_FINAL_MAN_FinalTradeStatisticsTables_31-07-21_WORKING.xlsx](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7690240/SEC_FINAL_MAN_FinalTradeStatisticsTables_31-07-21_WORKING.xlsx)

[SEC_PROC_ASY_RawDataAndReferenceTables_31-07-21.csv](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7690242/SEC_PROC_ASY_RawDataAndReferenceTables_31-07-21.csv)

[OUT_PROC_ASY_ProcessedRawData_31-07-21.csv](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/files/7690244/OUT_PROC_ASY_ProcessedRawData_31-07-21.csv)

There are few issues with Table 6 & 7- Principle Exports and Imports. Looking at July tables after code run- imports huge amount on yachts and vanilla, and some products missing.

However when look at data frame produced- the data looks right, so must be some issues in taking it from R and putting it into excel.

If you could take a look would be really appreciated.

**Comment by JosephCrispell** [comment]
Hi @hugo-e-pigott ,

Yes, I see there is something weird going on here. There is a clear spike for Vanilla and Yachts in the data:
![image](https://user-images.githubusercontent.com/17436210/145878451-f41ecfae-b505-4e6b-90a0-48573fba7c4f.png)

![image](https://user-images.githubusercontent.com/17436210/145878494-9eae5020-3c70-4171-9a7e-62dcb6132916.png)

I've found the issue, the order of the `columnCategories` variable has to match the order of rows in table (😢). I have updated the code and pushed changes to the [`monthly-trade-report`](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/tree/monthly-trade-report). Now above plots look more reasonable:

![image](https://user-images.githubusercontent.com/17436210/145882519-30d27807-fd11-41e5-a408-d6d29fc36275.png)

![image](https://user-images.githubusercontent.com/17436210/145882547-a0a2b98b-f33f-44c5-9116-1292a3c8dec6.png)

Added in a couple of crude code checks to warn if this happens again:

For table 6:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/e22f9f07ff58d91065b039a11a77a37c9000ac34/R/MonthlyReportAndTables/2_insertLatestMonthsDataIntoFormattedTables.R#L295-L307

And table 7:
https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/e22f9f07ff58d91065b039a11a77a37c9000ac34/R/MonthlyReportAndTables/2_insertLatestMonthsDataIntoFormattedTables.R#L395-L399

These are very crude code checks, which should be improved and similarly applied to all tables as relying on order leads to issues.

Thanks for flagging @hugo-e-pigott and I hope the above makes sense!

Joe
