### ISSUE TITLE
Some remaining tasks

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#118]
Have sent data-sets: 

- Raw & anonymised November 2021 (SEC_PROC_ASY_RawDataAndReferenceTables_30-11-21)
- Published tables (IMT_JULY-NOVEMBER_2021_FINAL)
- Tables produced in R with errors (SEC_FINAL_MAN_FinalTradeStatisticsTables_30-11-21_WORKING​)
- Processed & anonymised historical data from 2000 - 2021 August (exports-imports_historical_14.03.22)

Script 1 processing
- Have sent quite a long time getting all historic data into one place in same format. Need to write code to append processed data-sets into this. If could help with example code would be great

Script 2 tabulation
- Issues with table 6 & 7. Table 6 Principal Exports- the exports and re-exports are not summing correctly (attachment-tables produced in r highlighted in yellow from July onwards). Table 7 Principal Imports data-frame is produced correctly in R from what I can see but when extracted to excel some incorrect values (attachment- tables produced in r highlighted in yellow from July onwards). If could review this would be great

Script 3 report
(1st) DARD products are highlighted (fruit & veg imported); Trade balance by Major Partner Country (2nd) import country by HS; Principal Export- main country of destination etc. Need to develop tables for these so statistician can review and then write the text in report. If could help with producing tables (similar to cross tabs) looking at commodity and also what country being exported too with the statistical value etc, an example would be great again.

**Comment by jeroenminderman** [comment]
Hi @hugo-e-pigott thank you - will be having a look through this today and tomorrow and can hopefully suggest a few things for at least some of these.

**Comment by jeroenminderman** [comment]
Apologies @hugo-e-pigott, @NicciPotts and I are having issues replicating the processing script and thus difficult for us to tend to the above issues - I think we'll need to be able to fully reproduce the data processing and report building to effectively feed back on the above...

Current [script ](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/e2e813280e466d0bfa9fe481bd93746ba4253d56/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L27)references `SEC_PROC_ASY_RawDataAndReferenceTables_31-12-21.csv` but we have `SEC_PROC_ASY_RawDataAndReferenceTables_30-11-21.csv` in the folders you shared. Changing the date reference works ok but assume this means we're working with older data? Would it be possible to have the updated file please? 

Appear to be missing files referenced [here ](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/e2e813280e466d0bfa9fe481bd93746ba4253d56/R/MonthlyReportAndTables/1_processLatestMonthsTradeStats.R#L35-L36)also (`imports_HS_summaryStats_02-10-20.csv` and `exports_HS_summaryStats_02-10-20.csv`) - not in the secure data folder files @NicciPotts and I have and unsure what other files this might refer to?

Perhaps these files just need adding to the folders you shared?
