### ISSUE TITLE
Challenges with 13 Trade Tables

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#49]
– Issue with loading the "functions.R" file. Think this is my fault, on a previous merge the files conflicted, and so had to remove content to enable merge. Since then hasn't quite worked. Have investigated errors, they seem to be on "objects" within the code. Not sure but most likely small changes needed to get the file working again. 

– In the cleaning data section of the RMarkdown file have to include the calculation of the Unit Values & Boundary Values (previous work Joe has done). Then set up a system that flags values that fall outside these boundaries so that this data can potentially be replaced. 

– Missing data function have to add into it search for null values (both null and NULL). Again a system that flags this up to us so data can be replaced. Is it possible to write code that matches on data, so for missing or null values- we get potential values that can be used to replace? Will save us time in searching for right data. This point for data falling outside boundaries too (above). 

– Another error when with "function.R" when applying 'searchForMissingObservations'- again apologies mistake when merging previously.

– When data fully cleaned, and all classifications added, this data then integrated into the VNSO MYSQL database

– When merging Principle Commodities there is still a jump from 12540 to 12545 observations. Not sure why this is happening

Have been through the 13 tables, and quality checked agents cleaned dataset. However have not checked them all against Annas figures. The main challenge left is to take the DataFrame from the RMarkdown file and input this into an Excel file (a lot of transposing of data frames to get in right format). Below are Tables, with comments:

Table 1: Trade Balance- no issue
Table 2: Import by HS Code- no issue
Table 3: Export by HS Code- no issue
Table 4: ReExports by HS Code- no issue
Table 5: Total Exports by HS Code- no issue
Table 6: Principle Exports- no issue
Table 7: Principe imports- no issue
Table 8: Balance of Trade by Major Partner Countries- no issue
Table 9: Balance of Trade by Region- no issue
Table 10: Trade by Mode of Transport- error "undefined columns selected" have checked code and Excel file, not sure why
Table 11: Trade by Trade Agreement- have to write code to break down the variable MSG (is major trade agreement) found in "PRF" column, by SITC (sent previously a layout in Excel)
Table 12: Exports by SITC- no issue
Table 13: Imports by SITC- no issue

Have begun to work through some of the indicators for the International Trade Highlights Report- this included in branch after the code for tables. I still have to separate files as you previously wanted to have cleaning in R-file, and report in RMarkdown file. Will continue to work through and highlight challenges again for our next session.

**Comment by JosephCrispell** [comment]
Hi @hugo-e-pigott, I have resolved the issues with the code in `functions.R` script on all branches - this will fix problem with `searchForMissingObservations()` function as well.
