### ISSUE TITLE
Monthly Report Issues

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#86]
- [ ] NSDP Table
 * DataFrames for the NSDP indicators largely complete. Next step is to calculate whether these indicators are achieving their Targets, to do this we need Baseline data taken from the 2016 monthly report. This is because the NSDP was launched at the start of 2017. Working with Anna to get Raw data to calculate Baseline indicators can then calculate percentage increase or decrease in Trade for month we are reporting on. 
*  Need to take this data and merge it into the formatted tables, not sure how to do this. 

- [ ] Trade Balance by Major Partner Countries
 * If using a map, should have Key too
 * Again need to take this data and visualise it onto the map, not sure how to do this
 * Should also have a table or chart that highlights the countries and gives their Balance of Trade figures

- [ ] Trade Balance of Pacific Islands 
 * The DataFrame produced has positive Trade Balance, Zero Trade and Negative Trade Balance. Need to connect the countries that have positive and negative into a Bar Chart; for those that have Zero Trade maybe add them as a note- again not sure how to visualise this information.

- [x] Trade of Balance of New Emerging Markets
 * Have to create a subset of Trade Balances for all countries that fall into OTHER category. Then within this subset sort in ascending order (highest to lowest). Take the Top 5 (countries export a lot too) and Lost 5 (Countries import a lot from) and visualise this on a bar chart. Again not sure how to do this.

- [ ] Trade by Trade Agreement
 * Is possible to go through code, and how this extracts information from cleaned dataset. This Table is also incomplete in the Latest Monthly Table script (2).

- [ ] Principle Exports
 * Currently working with Anna to get data for major exports by month from 2010 to create a DataFrame to visualise. We will then be able to track trends on monthly basis. 

- [ ] Top 5 New Major Exports
 * This will be similar code to "Trade of Balance of New Emerging Markets" that not sure how to write

- [ ] Principle Imports
 * Currently working with Anna to get data for major imports by month from 2010 to create a DataFrame to visualise. We will then be able to track trends on monthly basis. 

- [ ] Top 5 New Major Imports
 * This will be similar code to "Trade of Balance of New Emerging Markets" that not sure how to write

- [ ] Methodology and Meta-Data
 * Haven't got to this stage yet, have to think through definitions, concepts, rationales and methodologies that want to include

**Comment by JosephCrispell** [comment]
@hugo-e-pigott I added code for "Trade of Balance of New Emerging Markets":

https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/e345dd4fa0d6a96890b81a82288901b42b343e9c/R/MonthlyReportAndTables/3_buildMonthlyReport.Rmd#L386-L428

Which gives the following chart: 
![image](https://user-images.githubusercontent.com/17436210/111299753-37640080-8648-11eb-888c-e06fcc3ad280.png)

Let me know what you think.
