### ISSUE TITLE
Updated code to use CSV

### ISSUE THREAD

**Issue by hugo-e-pigott** [Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials#92]
- Blank column in raw data that emerges, seems to be column X. How can I search Dataframe and remove empty column?
- Uploading in CSV loose leading zeros. Have changed format of columns in csv (ex 0000), however how can I do this in R?
- I've tried a few things but converting dates doesn't seem to be working. Closest I got was to have days with 4 figures (0008 for 8th)
- BEC still an issue have downloaded UN file and then mapped to our coding structure and definitions, there are duplicates though which mean when merge observations jumps up. I will go back and get rid of duplicates and re-try
- Code for missing observations not working
- Checking the confidence intervals isn't working properly

Code available branch [automated-highlights-report-new](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/tree/automated-highlights-report-new).

**Comment by JosephCrispell** [comment]
Hi @hugo-e-pigott,

I've created an simple R script where we can work on reading in the CSV file: [LoadCSVData.R](https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/automated-highlights-report-new/R/MonthlyReportAndTables/LoadCSVData.R).

To address your comments above:

- Blank column in raw data that emerges, seems to be column X. How can I search Dataframe and remove empty column?
  *We can identify and remove empty columns with the following code:*
  https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/f03a45a2eeacb2c9ea563f6176f370d35e7c5030/R/MonthlyReportAndTables/LoadCSVData.R#L29-L33
- Uploading in CSV loose leading zeros. Have changed format of columns in csv (ex 0000), however how can I do this in R?
  *Which column has the leading zeros - I can't see that in the raw data I have? The solution is probably to read the column in as a character (See `colClasses` parameter of `read.csv()` function).
- I've tried a few things but converting dates doesn't seem to be working. Closest I got was to have days with 4 figures (0008 for 8th)
  *For the `Reg. Date` column - best to read in as a character first, remove the repeated header, and then use `as.Date()` function:*
  https://github.com/Vanuatu-National-Statistics-Office/vnso-RAP-tradeStats-materials/blob/f03a45a2eeacb2c9ea563f6176f370d35e7c5030/R/MonthlyReportAndTables/LoadCSVData.R#L20-L26
- BEC still an issue have downloaded UN file and then mapped to our coding structure and definitions, there are duplicates though which mean when merge observations jumps up. I will go back and get rid of duplicates and re-try
  Remember you could use the `duplicated()` function in R to removed duplicated rows prior to merging.

**Comment by JosephCrispell** [comment]
While I've been working through the code there is a fair bit of cleaning up to do and making it more robust to minor changes (by introducing some flexibility and writing informative error messages). I don't think this is necessary for the launch but some to consider for the long term stability of the pipeline.
